import { GroupBox, HorizontalBox, VerticalBox } from "std-widgets.slint";

export component Skeleton {
    // WIP
    VerticalBox {
        Rectangle {
            border-radius: 20px;
            property <color> base-color: #d5d5d5;
            property <color> brighter-color: #c0c0c0;
            property <float> mix:abs(sin(360deg * animation-tick() / 3s));
            background: base-color.mix(brighter-color, mix);
            animate background { }
        }
    }
}
