[package]
name = "cxsign"
version = "0.1.0"
edition = "2021"
build = "build.rs" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
reqwest = { version = "0.11", features = ["json", "cookies", "gzip", "deflate", "multipart"] }
tokio = { version = "1.32", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.8"
ctrlc = "3.4"
regex = "1.9"
chinese-number = "0.7"
rand = "0.8"
utf8_slice = "1.0"
thread_local = "1.1"
trauma = "2.2"
tokio-stream = "*"
futures = "*"
url = "2.4"
percent-encoding = "2.3"
#strfmt = "*"
cookie_store = "*"
#cipher = { version = "0.4", features = ["block-padding"] }
#des = "0.8"
#ecb = "0.1"
#base64ct = "1.6"
#rust-crypto = "0.2.0"
#hex-literal = "0.4"
#hex = "0.4"
#des = "0.8"
#base64 = "0.21"
chrono = "0.4"
slint = "1.2"

[build-dependencies]
slint-build = "1.2"