[package]
name = "cxsign"
version = "0.1.0"
edition = "2021"
build = "build.rs"
auther = "worksoup"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = [
    "json",
    "cookies",
    "gzip",
    "deflate",
    "multipart",
] }
tokio = { version = "1.33", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tokio-stream = "0.1"
futures = "0.3"
url = "2.4"
percent-encoding = "2.3"
cookie_store = "0.20"
chrono = "0.4"
slint = "1.2"
image = "0.24"
clap = { version = "4.4", features = ["derive"] }
sqlite = "0.32"
inquire = "0.6"
directories = "5.0"
reqwest_cookie_store = "0.6"
lazy_static = "1.4"
unicode-width = "0.1"
rxing = "0.4"
# strfmt = "*"
# cipher = { version = "0.4", features = ["block-padding"] }
# des = "0.8"
# ecb = "0.1"
# base64ct = "1.6"
# rust-crypto = "0.2.0"
# hex-literal = "0.4"
# hex = "0.4"
# des = "0.8"
# base64 = "0.21"
# utf8_slice = "1.0"
# trauma = "2.2"
# chinese-number = "0.7"
# thread_local = "1.1"
# ctrlc = "3.4"
# regex = "1.10"
# toml = "0.8"
# rand = "0.8"

[build-dependencies]
slint-build = "1.2"
