[package]
name = "cxsign"
version = "0.1.0"
edition = "2021"
auther = "worksoup"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = { version = "4.4", features = ["derive"] }
cookie_store = "0.20"
des = "0.8"
directories = "5.0"
futures = "0.3"
hex-literal = "0.4"
hex = "0.4"
image = "0.24"
inquire = "0.6"
lazy_static = "1.4"
percent-encoding = "2.3"
reqwest = { version = "0.11", features = [
    "json",
    "cookies",
    "gzip",
    "deflate",
    "multipart",
] }
reqwest_cookie_store = "0.6"
rxing = "0.4.11"
screenshots = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
sqlite = "0.32"
tokio = { version = "1.34", features = ["full"] }
tokio-stream = "0.1"
unicode-width = "0.1"
# slint = "1.2"
# url = "2.4"
# strfmt = "*"
# cipher = { version = "0.4", features = ["block-padding"] }
# ecb = "0.1"
# base64ct = "1.6"
# rust-crypto = "0.2.0"
# hex-literal = "0.4"
# base64 = "0.21"
# utf8_slice = "1.0"
# trauma = "2.2"
# chinese-number = "0.7"
# thread_local = "1.1"
# ctrlc = "3.4"
# regex = "1.10"
# toml = "0.8"
# rand = "0.8"

[build-dependencies]
slint-build = "1.2"
