import { ListView } from "std-widgets.slint";

export struct UserListItem {
    name: string,
    avatar: image,
    teacher: string,
}

component UserWidget {
    in property <string> name: "Name";
    in property <image> avatar: @image-url("../assets/icon/account.svg");
    in property <string> teacher: "Teacher";
    HorizontalLayout {
        HorizontalLayout{
            alignment: start;
            Image {
                min-height: 32px;
                min-width: 32px;
                preferred-height: 32px;
                preferred-width: 32px;
                source: avatar;
            }
        }
        HorizontalLayout{
            alignment: center;
            VerticalLayout {
                alignment: center;
                name-text:= Text {
                    horizontal-alignment: left;
                    text: name;
                }
                Text {
                    horizontal-alignment: left;
                    font-size: 10px;
                    text: teacher;
                    color: gray;
                }
            }
        }
    }
}
export component UserList {
    in property <[UserListItem]> accounts: [
        {name: "Name", avatar: @image-url("../assets/icon/account.svg"), teacher: "Teacher"},
        {name: "Name", avatar: @image-url("../assets/icon/account.svg"), teacher: "Teacher"},
        {name: "Name", avatar: @image-url("../assets/icon/account.svg"), teacher: "Teacher"},
        {name: "Name", avatar: @image-url("../assets/icon/account.svg"), teacher: "Teacher"},
        {name: "Name", avatar: @image-url("../assets/icon/account.svg"), teacher: "Teacher"},
        {name: "Name", avatar: @image-url("../assets/icon/account.svg"), teacher: "Teacher"},
        {name: "Name", avatar: @image-url("../assets/icon/account.svg"), teacher: "Teacher"},
        {name: "Name", avatar: @image-url("../assets/icon/account.svg"), teacher: "Teacher"},
        {name: "Name", avatar: @image-url("../assets/icon/account.svg"), teacher: "Teacher"},
    ];
    ListView {
        for account in accounts: UserWidget {
            name: account.name;
            avatar: account.avatar;
            teacher: account.teacher;
        }
    }
}