[package]
name = "types"
version.workspace = true
authors.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dir = { path = "../dir" }
user = { path = "../user" }
serde = { workspace = true, features = ["derive"] }
rand = "0.8"
ureq = { workspace = true, features = ["cookies", "json"] }
pan = { path = "../pan" }