
import { GroupBox , Button} from "std-widgets.slint";
import { LoginWidget } from "login-widget.slint";
import { MainWidget } from "main-widget.slint";
import { CourseListItem } from "course-widget.slint";
import { ActivityListItem } from "activity-widget.slint";
import { UserListItem } from "user-widget.slint";

export enum MainPage{ login-page, main-page }

export component MainWindow inherits Window {
    callback login(string,string);
    in-out property <MainPage> page;
    in property <bool> login-widget-enabled: true;
    in property <[CourseListItem]> courses;
    in property <[ActivityListItem]> activities;
    in property <[UserListItem]> accounts;

    if page==MainPage.login-page: login-widget:= LoginWidget {
        enabled: login-widget-enabled;
        clicked => {
            login(login-widget.uname, login-widget.pwd);
        }
    }
    if page==MainPage.main-page: main-widget:= MainWidget {
        courses: courses;
        activities: activities;
        accounts: accounts;
        width: parent.width;
        height: parent.height;
    }
}
export { CourseListItem, ActivityListItem, UserListItem }