name: Rust Build and Release

on:
  push:
    branches: [ "slint-ui-dev" ]
  pull_request:
    branches: [ "slint-ui-dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest # 或 windows-latest / macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --verbose --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cxsign-binary
        path: target/release/cxsign # 假设可执行文件名为 cxsign
